[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[etherscan]
sophon_testnet = { key = "${ETHERSCAN_SOPHON_API_KEY}", url = "https://api-testnet.sophon.xyz/api" }
sophon_mainnet = { key = "${ETHERSCAN_SOPHON_API_KEY}", url = "https://api.sophon.xyz/api" }

[rpc_endpoints]
sophon_testnet = "${SOPHON_TESTNET_RPC_URL}"
sophon_mainnet = "${SOPHON_MAINNET_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
