[profile.default]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.24"
src = "src"
via_ir = true
fallback_oz = true
mode = "3"
suppressedWarnings = ["assemblycreate"]

[etherscan]
sophon_testnet = {key = "${ETHERSCAN_SOPHON_API_KEY}", url = "https://explorer.testnet.sophon.xyz/api", chain = 531050104}
# sophon_mainnet = { key = "${ETHERSCAN_SOPHON_API_KEY}", url = "https://explorer.sophon.xyz/api", chain = 50104 }

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sophonMainnet = "${SOPHON_MAINNET_RPC_URL}"
sophonTestnet = "${SOPHON_TESTNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
